/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pbs;

//import javaapplication2.ProffOak;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import newpackage.Pokemon;

/**
 *
 * @author Mahe
 */
public class BuildTeam extends javax.swing.JFrame {

    /**
     * Creates new form BuildTeam
     */
    static String user;
    String P1 , P2 , P3 ;
    String M11,M12,M13,M14;
    String M21,M22,M23,M24;
    String M31,M32,M33,M34;
    File f = null;
    int linesread = 1;
    String url="jdbc:oracle:thin:@DESKTOP-08UAP4B:1521:XE";
    String username="push";
    String password="umsy0410";
    public BuildTeam(String abc) {
        user=abc;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jComboBox3 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox();
        jComboBox5 = new javax.swing.JComboBox();
        jComboBox6 = new javax.swing.JComboBox();
        jComboBox7 = new javax.swing.JComboBox();
        jComboBox8 = new javax.swing.JComboBox();
        jComboBox9 = new javax.swing.JComboBox();
        jComboBox10 = new javax.swing.JComboBox();
        jComboBox11 = new javax.swing.JComboBox();
        jComboBox12 = new javax.swing.JComboBox();
        jComboBox13 = new javax.swing.JComboBox();
        jComboBox14 = new javax.swing.JComboBox();
        jComboBox15 = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(653, 432));
        getContentPane().setLayout(null);

        jTextField1.setText("jTextField1");
        getContentPane().add(jTextField1);
        jTextField1.setBounds(39, 295, 601, 55);

        jComboBox1.setEditable(true);
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Balbasaur", "Abra", "Charmander", "Squirtle", "Caterpie", "Weedle", "Pidgey", "Rattata", "Spearow", "Ekans", "Pikachu", "Sandshrew", "Nidoran(male)", "Nidoran(Female)", "Cleffa", "Vulpix", "Iigglypuff", "Zubat", "Oddish", "Paras", "Venonat", "Diglett", "Meowth", "Psyduck", "Mankey", "Growlithe", "Poliwag", "Abra", "Machop", "Bellsprout", "Tentacool", "Geodude", "Ponyta", "Slowpoke", "Magnemite", "Farfetch'd", "Doduo", "Seel", "Grimer", "Shellder", "Gastly", "Onix", "Drowzee", "Krabby", "Voltorb", "Exeggcute", "Cubone", "Tyrouge", "Lickitung", "Koffing", "Rhyhorn", "Happiny", "Tangela", "Kangaskhan", "Horsea", "Goldeen", "Staryu", "Mr.Mime", "Scyther", "Jynx", "Elekid", "Magby", "Pinsir", "Tauros", "Magikarp", "Lapras", "Ditto", "Eevee", "Omanyte", "Kabuto", "Aerodactyl", "Munchlax", "Dratini" }));
        jComboBox1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(39, 167, 89, 22);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Balbasaur", "Charmander", "Squirtle", "Caterpie", "Weedle", "Pidgey", "Rattata", "Spearow", "Ekans", "Pikachu", "Sandshrew", "Nidoran(male)", "Nidoran(Female)", "Cleffa", "Vulpix", "Iigglypuff", "Zubat", "Oddish", "Paras", "Venonat", "Diglett", "Meowth", "Psyduck", "Mankey", "Growlithe", "Poliwag", "Abra", "Machop", "Bellsprout", "Tentacool", "Geodude", "Ponyta", "Slowpoke", "Magnemite", "Farfetch'd", "Doduo", "Seel", "Grimer", "Shellder", "Gastly", "Onix", "Drowzee", "Krabby", "Voltorb", "Exeggcute", "Cubone", "Tyrouge", "Lickitung", "Koffing", "Rhyhorn", "Happiny", "Tangela", "Kangaskhan", "Horsea", "Goldeen", "Staryu", "Mr.Mime", "Scyther", "Jynx", "Elekid", "Magby", "Pinsir", "Tauros", "Magikarp", "Lapras", "Ditto", "Eevee", "Omanyte", "Kabuto", "Aerodactyl", "Munchlax", "Dratini" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(268, 167, 123, 22);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Balbasaur", "Charmander", "Squirtle", "Caterpie", "Weedle", "Pidgey", "Rattata", "Spearow", "Ekans", "Pikachu", "Sandshrew", "Nidoran(male)", "Nidoran(Female)", "Cleffa", "Vulpix", "Iigglypuff", "Zubat", "Oddish", "Paras", "Venonat", "Diglett", "Meowth", "Psyduck", "Mankey", "Growlithe", "Poliwag", "Abra", "Machop", "Bellsprout", "Tentacool", "Geodude", "Ponyta", "Slowpoke", "Magnemite", "Farfetch'd", "Doduo", "Seel", "Grimer", "Shellder", "Gastly", "Onix", "Drowzee", "Krabby", "Voltorb", "Exeggcute", "Cubone", "Tyrouge", "Lickitung", "Koffing", "Rhyhorn", "Happiny", "Tangela", "Kangaskhan", "Horsea", "Goldeen", "Staryu", "Mr.Mime", "Scyther", "Jynx", "Elekid", "Magby", "Pinsir", "Tauros", "Magikarp", "Lapras", "Ditto", "Eevee", "Omanyte", "Kabuto", "Aerodactyl", "Munchlax", "Dratini" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox3);
        jComboBox3.setBounds(499, 167, 123, 22);

        jButton1.setText("Continue ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(39, 386, 87, 25);

        jButton2.setText("Next");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(541, 386, 57, 25);

        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(39, 50, 41, 16);

        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(268, 50, 41, 16);

        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(499, 50, 41, 16);

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox4);
        jComboBox4.setBounds(39, 220, 64, 22);

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox5);
        jComboBox5.setBounds(134, 220, 64, 22);

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox6);
        jComboBox6.setBounds(39, 255, 64, 22);

        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox7);
        jComboBox7.setBounds(134, 255, 64, 22);

        jComboBox8.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox8);
        jComboBox8.setBounds(268, 220, 64, 22);

        jComboBox9.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox9);
        jComboBox9.setBounds(350, 220, 64, 22);

        jComboBox10.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox10);
        jComboBox10.setBounds(268, 255, 64, 22);

        jComboBox11.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox11);
        jComboBox11.setBounds(350, 255, 64, 22);

        jComboBox12.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox12);
        jComboBox12.setBounds(499, 220, 64, 22);

        jComboBox13.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox13);
        jComboBox13.setBounds(576, 220, 64, 22);

        jComboBox14.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox14);
        jComboBox14.setBounds(499, 260, 64, 22);

        jComboBox15.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox15);
        jComboBox15.setBounds(576, 260, 64, 22);

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Pushkar\\Desktop\\images\\3_653x432.jpg")); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(2, 2, 650, 430);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
         String path = (String)jComboBox2.getSelectedItem();
        ImageIcon icon1 = new ImageIcon("D:\\PBS_Final\\PBS\\Images\\" +path+".png" );
        jLabel2.setIcon(icon1);
        
        
        jComboBox8.removeAllItems();
        jComboBox9.removeAllItems();
        jComboBox10.removeAllItems();
        jComboBox11.removeAllItems();
        
        
         int linesread = 0;
        String s = null;
        f = new File("D:\\PBS_Final\\PBS\\MoveSet\\"+path+".txt");
        BufferedReader b=null;
        try {
             b = new BufferedReader(new FileReader(f));
        } catch (FileNotFoundException ex) {
            Logger.getLogger(BuildTeam.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            while((s=b.readLine())!=null)
            {
               jComboBox8.addItem(s);
               jComboBox9.addItem(s);
               jComboBox10.addItem(s);
               jComboBox11.addItem(s);
               
            }
        } catch (IOException ex) {
            Logger.getLogger(BuildTeam.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        String path = (String)jComboBox1.getSelectedItem();
        ImageIcon icon1 = new ImageIcon("D:\\PBS_Final\\PBS\\Images\\" +path+".png" );
        jLabel1.setIcon(icon1);
        
        jComboBox4.removeAllItems();
        jComboBox5.removeAllItems();
        jComboBox6.removeAllItems();
        jComboBox7.removeAllItems();
        int linesread = 0;
        String s = null;
        f = new File("D:\\PBS_Final\\PBS\\Moveset\\"+path+".txt");
        BufferedReader b=null;
        try {
             b = new BufferedReader(new FileReader(f));
        } catch (FileNotFoundException ex) {
            Logger.getLogger(BuildTeam.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            while((s=b.readLine())!=null)
            {
               jComboBox4.addItem(s);
               jComboBox5.addItem(s);
               jComboBox6.addItem(s);
               jComboBox7.addItem(s);
               
            }
        } catch (IOException ex) {
            Logger.getLogger(BuildTeam.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        P1 = jComboBox1.getSelectedItem().toString();M11 = jComboBox4.getSelectedItem().toString();M12 = jComboBox5.getSelectedItem().toString();M13 = jComboBox6.getSelectedItem().toString();M14 = jComboBox7.getSelectedItem().toString();
        P2 = jComboBox2.getSelectedItem().toString();M21 =  jComboBox8.getSelectedItem().toString();M22 =  jComboBox9.getSelectedItem().toString();M23 =  jComboBox10.getSelectedItem().toString();M24 =  jComboBox11.getSelectedItem().toString();
        P3 = jComboBox3.getSelectedItem().toString();M31 =  jComboBox12.getSelectedItem().toString();M32 =  jComboBox13.getSelectedItem().toString();M33 =  jComboBox14.getSelectedItem().toString();M34 =  jComboBox15.getSelectedItem().toString();
        try{
            Connection conn=DriverManager.getConnection(url,username,password);
            Statement stmt1=conn.createStatement();
            Statement stmt=conn.createStatement();
            stmt.executeQuery("update trainer_pokemon set flag=0 where trainer_id='"+user+"'");
            ResultSet rs=stmt1.executeQuery("select * from trainer_pokemon where trainer_id='"+user+"' and  pokemon='"+P1+"'");
            if(rs.next())
            {
                Statement stmt2=conn.createStatement();
                stmt2.executeQuery("update trainer_pokemon set flag=1 where trainer_id='"+user+"' and pokemon='"+P1+"'");
            }
            else
            {
                Statement stmt3=conn.createStatement();
                stmt3.executeQuery("insert into trainer_pokemon(trainer_id,pokemon,m1,m2,m3,m4) values('"+user+"','"+P1+"','"+M11+"','"+M12+"','"+M13+"','"+M14+"')");
            }
            ResultSet rs1=stmt1.executeQuery("select * from trainer_pokemon where trainer_id='"+user+"' and  pokemon='"+P2+"'");
            if(rs1.next())
            {
                Statement stmt2=conn.createStatement();
                stmt2.executeQuery("update trainer_pokemon set flag=1 where trainer_id='"+user+"' and pokemon='"+P2+"'");
            }
            else
            {
                Statement stmt3=conn.createStatement();
                stmt3.executeQuery("insert into trainer_pokemon(trainer_id,pokemon,m1,m2,m3,m4) values('"+user+"','"+P2+"','"+M21+"','"+M22+"','"+M23+"','"+M24+"')");
            }
            ResultSet rs2=stmt1.executeQuery("select * from trainer_pokemon where trainer_id='"+user+"' and  pokemon='"+P3+"'");
            if(rs2.next())
            {
                Statement stmt2=conn.createStatement();
                stmt2.executeQuery("update trainer_pokemon set flag=1 where trainer_id='"+user+"' and pokemon='"+P3+"'");
            }
            else
            {
                Statement stmt3=conn.createStatement();
                stmt3.executeQuery("insert into trainer_pokemon(trainer_id,pokemon,m1,m2,m3,m4) values('"+user+"','"+P3+"','"+M31+"','"+M32+"','"+M33+"','"+M34+"')");
            }
            
            
            
            
        }
        
        catch(Exception e){
            System.out.println(e.getMessage());
        }
        //Pokemon Pk1 = new Pokemon(P1,M11,M12,M13,M14);
        //Pokemon Pk2 = new Pokemon(P2,M21,M22,M23,M24);
        //Pokemon Pk3 = new Pokemon(P3,M31,M32,M33,M34);
        //BattleOptions f = new BattleOptions(P1,P2,P3);
        if(user.equals("gym1"))
        {
            try{
            Connection conn=DriverManager.getConnection(url,username,password);
            Statement stmt1=conn.createStatement();
            //ResultSet rs=stmt1.executeQuery("select level from trainer_pokemon where")
            
            
            stmt1.executeQuery("update trainer_pokemon set lev="+2+" where trainer_id='gym1'");
        
        }
        
        catch(Exception e){
            System.out.println(e.getMessage());
        }
            this.setVisible(false);
            new Admin().setVisible(true);
        }
        else if(user.equals("gym2"))
        {
            try{
            Connection conn=DriverManager.getConnection(url,username,password);
            Statement stmt1=conn.createStatement();
            //ResultSet rs=stmt1.executeQuery("select level from trainer_pokemon where")
            
            
            stmt1.executeQuery("update trainer_pokemon set lev="+4+" where trainer_id='gym2'");
        
        }
        
        catch(Exception e){
            System.out.println(e.getMessage());
        }
            this.setVisible(false);
            new Admin().setVisible(true);
        }
        else if(user.equals("gym3"))
        {
            try{
            Connection conn=DriverManager.getConnection(url,username,password);
            Statement stmt1=conn.createStatement();
            //ResultSet rs=stmt1.executeQuery("select level from trainer_pokemon where")
            
            
            stmt1.executeQuery("update trainer_pokemon set lev="+6+" where trainer_id='gym3'");
        
        }
        
        catch(Exception e){
            System.out.println(e.getMessage());
        }
            this.setVisible(false);
            new Admin().setVisible(true);
        }
        else if(user.equals("gym4"))
        {
            try{
            Connection conn=DriverManager.getConnection(url,username,password);
            Statement stmt1=conn.createStatement();
            //ResultSet rs=stmt1.executeQuery("select level from trainer_pokemon where")
            
            
            stmt1.executeQuery("update trainer_pokemon set lev="+8+" where trainer_id='gym4'");
        
        }
        
        catch(Exception e){
            System.out.println(e.getMessage());
        }
            this.setVisible(false);
            new Admin().setVisible(true);
        }
        else{
        this.setVisible(false);
        BattleOptions f = new BattleOptions(user);
        f.setVisible(true);}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        f = new File("D:\\PBS_Final\\PBS\\Images\\BuildTeamInst.txt");
        BufferedReader b = null;
        try {
            b = new BufferedReader(new FileReader(f));
        } catch (FileNotFoundException ex) {
            Logger.getLogger(ProffOak.class.getName()).log(Level.SEVERE, null, ex);
        }
        String s = null;
        for(int i = 0 ; i < linesread ; i++)
        {   
            try {
                
                s = b.readLine();
            }  catch (IOException ex) {
                Logger.getLogger(ProffOak.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        linesread++;
        jTextField1.setText(s);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
         String path = (String)jComboBox3.getSelectedItem();
        ImageIcon icon1 = new ImageIcon("D:\\PBS_Final\\PBS\\Images\\" +path+".png" );
        jLabel3.setIcon(icon1);
        
        jComboBox12.removeAllItems();
        jComboBox13.removeAllItems();
        jComboBox14.removeAllItems();
        jComboBox15.removeAllItems();
        
         int linesread = 0;
        String s = null;
        f = new File("D:\\PBS_Final\\PBS\\Moveset\\"+path+".txt");
        BufferedReader b=null;
        try {
             b = new BufferedReader(new FileReader(f));
        } catch (FileNotFoundException ex) {
            Logger.getLogger(BuildTeam.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            while((s=b.readLine())!=null)
            {
               jComboBox12.addItem(s);
               jComboBox13.addItem(s);
               jComboBox14.addItem(s);
               jComboBox15.addItem(s);
               
            }
        } catch (IOException ex) {
            Logger.getLogger(BuildTeam.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jComboBox3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuildTeam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuildTeam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuildTeam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuildTeam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuildTeam(user).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox10;
    private javax.swing.JComboBox jComboBox11;
    private javax.swing.JComboBox jComboBox12;
    private javax.swing.JComboBox jComboBox13;
    private javax.swing.JComboBox jComboBox14;
    private javax.swing.JComboBox jComboBox15;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JComboBox jComboBox5;
    private javax.swing.JComboBox jComboBox6;
    private javax.swing.JComboBox jComboBox7;
    private javax.swing.JComboBox jComboBox8;
    private javax.swing.JComboBox jComboBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
