/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pbs;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;
import newpackage.Pokemon;
//import static pbs.BattleOptions.user;

/**
 *
 * @author Pushkar
 */

public class Gyms extends javax.swing.JFrame {

    /**
     * Creates new form Gyms
     */
    String url="jdbc:oracle:thin:@DESKTOP-08UAP4B:1521:XE";
    String username="push";
    String password="umsy0410";
    
    Pokemon P1,P2,P3,Y1,Y2,Y3;
    static String user;
    public Gyms(String abc) {
        user=abc;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(718, 405));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        jButton1.setText("GYM1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(95, 36, 65, 25);

        jButton2.setText("GYM2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(100, 120, 65, 25);

        jButton3.setText("GYM3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(95, 188, 65, 25);

        jButton4.setText("GYM4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(95, 307, 65, 25);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "1", "2", "3", "4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(213, 85, 398, 202);

        jButton5.setText("Back");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(630, 13, 59, 25);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Pushkar\\Desktop\\images\\7_718x405.jpg")); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(1, -4, 720, 410);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        DefaultTableModel tb11=(DefaultTableModel)jTable1.getModel();
        try{
            Connection conn=DriverManager.getConnection(url,username,password);
            Statement stmt1=conn.createStatement();
            
            
            
            ResultSet rs1=stmt1.executeQuery("select * from trainer_gym where trainer_id='"+user+"'");
            tb11.setRowCount(0);
            while(rs1.next()){
                Object row1[]=new Object[4];
                row1[0]=rs1.getObject(2).toString();
                row1[1]=rs1.getObject(3).toString(); 
                row1[2]=rs1.getObject(4).toString(); 
                row1[3]=rs1.getObject(5).toString(); 
                //row1[4]=rs1.getObject(6).toString();
                tb11.addRow(row1);
            
            
        }
            }
        
        catch(Exception e){
            System.out.println(e.getMessage());
        }
        try{
            Connection conn=DriverManager.getConnection(url,username,password);
            Statement stmt1=conn.createStatement();
            Statement stmt=conn.createStatement();
            
            ResultSet rs1=stmt.executeQuery("select * from trainer_pokemon where trainer_id='"+user+"' and flag=1");
            rs1.next();
                
                
                String poke_name=rs1.getObject(2).toString();
                int level=rs1.getInt(3);
                String m1=rs1.getObject(4).toString(); 
                String m2=rs1.getObject(5).toString(); 
                String m3=rs1.getObject(6).toString(); 
                String m4=rs1.getObject(7).toString();
                P1= new Pokemon(poke_name,level,m1,m2,m3,m4);
                rs1.next();
                poke_name=rs1.getObject(2).toString();
                level=rs1.getInt(3);
                m1=rs1.getObject(4).toString(); 
                m2=rs1.getObject(5).toString(); 
                m3=rs1.getObject(6).toString(); 
                m4=rs1.getObject(7).toString();
                P2= new Pokemon(poke_name,level,m1,m2,m3,m4);
                rs1.next();
                poke_name=rs1.getObject(2).toString();
                level=rs1.getInt(3);
                m1=rs1.getObject(4).toString(); 
                m2=rs1.getObject(5).toString(); 
                m3=rs1.getObject(6).toString(); 
                m4=rs1.getObject(7).toString();
                P3= new Pokemon(poke_name,level,m1,m2,m3,m4);
                
                
               
            
            
        
        }
        catch(Exception e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_formWindowActivated

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
            Connection conn=DriverManager.getConnection(url,username,password);
            Statement stmt1=conn.createStatement();
            
            
            
            ResultSet rs1=stmt1.executeQuery("select * from trainer_pokemon where trainer_id='gym1'");
            rs1.next();
                
                
                String poke_name=rs1.getObject(2).toString();
                int level=rs1.getInt(3);
                String m1=rs1.getObject(4).toString(); 
                String m2=rs1.getObject(5).toString(); 
                String m3=rs1.getObject(6).toString(); 
                String m4=rs1.getObject(7).toString();
                Y1= new Pokemon(poke_name,level,m1,m2,m3,m4);
                rs1.next();
                poke_name=rs1.getObject(2).toString();
                level=rs1.getInt(3);
                m1=rs1.getObject(4).toString(); 
                m2=rs1.getObject(5).toString(); 
                m3=rs1.getObject(6).toString(); 
                m4=rs1.getObject(7).toString();
                Y2= new Pokemon(poke_name,level,m1,m2,m3,m4);
                rs1.next();
                poke_name=rs1.getObject(2).toString();
                level=rs1.getInt(3);
                m1=rs1.getObject(4).toString(); 
                m2=rs1.getObject(5).toString(); 
                m3=rs1.getObject(6).toString(); 
                m4=rs1.getObject(7).toString();
                Y3= new Pokemon(poke_name,level,m1,m2,m3,m4);
            this.setVisible(false);
                new ThreeVsThree_gym(user,1,P1,P2,P3,Y1,Y2,Y3).setVisible(true);
            
        }
        
        catch(Exception e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try{
            Connection conn=DriverManager.getConnection(url,username,password);
            Statement stmt1=conn.createStatement();
            
            
            
            ResultSet rs1=stmt1.executeQuery("select * from trainer_pokemon where trainer_id='gym2'");
            rs1.next();
                
                
                String poke_name=rs1.getObject(2).toString();
                int level=rs1.getInt(3);
                String m1=rs1.getObject(4).toString(); 
                String m2=rs1.getObject(5).toString(); 
                String m3=rs1.getObject(6).toString(); 
                String m4=rs1.getObject(7).toString();
                Y1= new Pokemon(poke_name,level,m1,m2,m3,m4);
                rs1.next();
                poke_name=rs1.getObject(2).toString();
                level=rs1.getInt(3);
                m1=rs1.getObject(4).toString(); 
                m2=rs1.getObject(5).toString(); 
                m3=rs1.getObject(6).toString(); 
                m4=rs1.getObject(7).toString();
                Y2= new Pokemon(poke_name,level,m1,m2,m3,m4);
                rs1.next();
                poke_name=rs1.getObject(2).toString();
                level=rs1.getInt(3);
                m1=rs1.getObject(4).toString(); 
                m2=rs1.getObject(5).toString(); 
                m3=rs1.getObject(6).toString(); 
                m4=rs1.getObject(7).toString();
                Y3= new Pokemon(poke_name,level,m1,m2,m3,m4);
                
                this.setVisible(false);
                new ThreeVsThree_gym(user,2,P1,P2,P3,Y1,Y2,Y3).setVisible(true);
            
            
        }
        
        catch(Exception e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try{
            Connection conn=DriverManager.getConnection(url,username,password);
            Statement stmt1=conn.createStatement();
            
            
            
            ResultSet rs1=stmt1.executeQuery("select * from trainer_pokemon where trainer_id='gym3'");
            rs1.next();
                
                
                String poke_name=rs1.getObject(2).toString();
                int level=rs1.getInt(3);
                String m1=rs1.getObject(4).toString(); 
                String m2=rs1.getObject(5).toString(); 
                String m3=rs1.getObject(6).toString(); 
                String m4=rs1.getObject(7).toString();
                Y1= new Pokemon(poke_name,level,m1,m2,m3,m4);
                rs1.next();
                poke_name=rs1.getObject(2).toString();
                level=rs1.getInt(3);
                m1=rs1.getObject(4).toString(); 
                m2=rs1.getObject(5).toString(); 
                m3=rs1.getObject(6).toString(); 
                m4=rs1.getObject(7).toString();
                Y2= new Pokemon(poke_name,level,m1,m2,m3,m4);
                rs1.next();
                poke_name=rs1.getObject(2).toString();
                level=rs1.getInt(3);
                m1=rs1.getObject(4).toString(); 
                m2=rs1.getObject(5).toString(); 
                m3=rs1.getObject(6).toString(); 
                m4=rs1.getObject(7).toString();
                Y3= new Pokemon(poke_name,level,m1,m2,m3,m4);
                
                this.setVisible(false);
                new ThreeVsThree_gym(user,3,P1,P2,P3,Y1,Y2,Y3).setVisible(true);
            
            
        }
        
        catch(Exception e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try{
            Connection conn=DriverManager.getConnection(url,username,password);
            Statement stmt1=conn.createStatement();
            
            
            
            ResultSet rs1=stmt1.executeQuery("select * from trainer_pokemon where trainer_id='gym4'");
            rs1.next();
                
                
                String poke_name=rs1.getObject(2).toString();
                int level=rs1.getInt(3);
                String m1=rs1.getObject(4).toString(); 
                String m2=rs1.getObject(5).toString(); 
                String m3=rs1.getObject(6).toString(); 
                String m4=rs1.getObject(7).toString();
                Y1= new Pokemon(poke_name,level,m1,m2,m3,m4);
                rs1.next();
                poke_name=rs1.getObject(2).toString();
                level=rs1.getInt(3);
                m1=rs1.getObject(4).toString(); 
                m2=rs1.getObject(5).toString(); 
                m3=rs1.getObject(6).toString(); 
                m4=rs1.getObject(7).toString();
                Y2= new Pokemon(poke_name,level,m1,m2,m3,m4);
                rs1.next();
                poke_name=rs1.getObject(2).toString();
                level=rs1.getInt(3);
                m1=rs1.getObject(4).toString(); 
                m2=rs1.getObject(5).toString(); 
                m3=rs1.getObject(6).toString(); 
                m4=rs1.getObject(7).toString();
                Y3= new Pokemon(poke_name,level,m1,m2,m3,m4);
                
                this.setVisible(false);
                new ThreeVsThree_gym(user,4,P1,P2,P3,Y1,Y2,Y3).setVisible(true);
            
            
        }
        
        catch(Exception e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        this.setVisible(false);
        new BattleOptions(user).setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gyms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gyms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gyms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gyms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gyms(user).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
